[package]

name = "housecat"
version = "0.0.0"
authors = [ "whenderson" ]

[lib]
name = "housecat"
path = "src/lib.rs"

[[bin]]
name = "housecat-cli"
path = "src/main.rs"

[dependencies]
regex = "0.1.58"
num = "0.1.31"
